# Generated by Django 2.2 on 2020-07-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kosbiz_app', '0003_auto_20200719_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdays',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bussinesaddress',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessdays',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosbiz_app.Business'),
        ),
        migrations.AlterField(
            model_name='bussinesaddress',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kosbiz_app.Business'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kosbiz_app.UserAddress'),
        ),
    ]
