# Generated by Django 2.2 on 2020-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosbiz_app', '0004_auto_20200719_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdays',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
