# Generated by Django 2.2 on 2020-07-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosbiz_app', '0005_auto_20200719_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussinesaddress',
            old_name='stret_address',
            new_name='street',
        ),
    ]
