# Generated by Django 2.2 on 2020-07-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosbiz_app', '0006_auto_20200719_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
