# Generated by Django 2.2 on 2020-07-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kosbiz_app', '0009_auto_20200719_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='kosbiz_app.User'),
        ),
        migrations.AlterField(
            model_name='businessdays',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_days', to='kosbiz_app.Business'),
        ),
        migrations.AlterField(
            model_name='bussinesaddress',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='kosbiz_app.Business'),
        ),
        migrations.CreateModel(
            name='BusinessReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reviews', to='kosbiz_app.Business')),
            ],
        ),
    ]
