# Generated by Django 2.2 on 2020-07-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosbiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='store',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='BusinessHours',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
