# Generated by Django 2.2 on 2020-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosbiz_app', '0011_businessreviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
